# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- name: Install the Intel libsgx package dependencies
  yum:
    name: "{{ intel_sgx_package_dependencies }}"
    state: latest
  retries: 10
  register: install_sgx_dependencies
  until: install_sgx_dependencies is success

- name: Create Intel SGX directory
  file:
    path: "{{ intel_sgx_directory }}"
    state: directory

- name: Download Intel SGX local rpm repo tgz
  get_url:
    url: "{{ intel_sgx_rpm_repo_tgz_url }}"
    dest: "/tmp/sgx_rpm_local_repo.tgz"
    timeout: 120
  retries: 5

- name: Unarchive Intel SGX local rpm repo tgz
  unarchive:
    src: "/tmp/sgx_rpm_local_repo.tgz"
    dest: "{{ intel_sgx_directory }}"
    remote_src: yes

- name: Enable local Intel SGX repo
  yum_repository:
    name: intel-sgx-local-repo
    description: Intel SGX local RPM repository
    baseurl: "file://{{ intel_sgx_directory }}/sgx_rpm_local_repo"
    enabled: yes
    gpgcheck: no

- name: Install Intel SGX packages
  yum:
    name: "{{ intel_sgx_packages }}"
    state: latest
  retries: 10
  register: install_sgx
  until: install_sgx is success

- name: Download Intel SGX DCAP Packages
  get_url:
    url: "{{ intel_dcap_packages_url }}"
    dest: "/tmp/"
    mode: 0755
    timeout: 120
  retries: 3
  when: flc_enabled|bool
  register: get_dcap_package

- name: Create Intel DCAP directory
  file:
    path: "{{ intel_dcap_packages_directory }}"
    state: directory

- name: Clean local rpm repo if it exists
  file:
    path: "{{ intel_dcap_packages_directory }}/sgx_rpm_local_repo"
    state: absent

- name: Unarchive Intel DCAP local rpm repo tgz
  unarchive:
    src: "{{ get_dcap_package.dest }}"
    dest: "{{ intel_dcap_packages_directory }}"
    remote_src: yes
  when:
    - get_dcap_package.changed
    - get_dcap_package.dest

- name: Enable local Intel DCAP repo
  yum_repository:
    name: intel-dcap-local-repo
    description: Intel DCAP local RPM repository
    baseurl: "file://{{ intel_dcap_packages_directory }}/sgx_rpm_local_repo"
    enabled: no
    gpgcheck: no

- name: Install Intel DCAP packages
  yum:
    name: "{{ intel_dcap_packages }}"
    state: present
    enablerepo: intel-dcap-local-repo
  when: flc_enabled|bool
  retries: 10
  register: install_dcap
  until: install_dcap is success

- name: Cleanup installation
  file:
    path: "{{ get_dcap_package.dest }}"
    state: absent
